apps/threads/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.forms import UserCreationForm
from apps.threads.views import (
LinkListView, logout_view, auth, subreddit_view, subreddit_selector,
link_discuss, submit_link, register, vote_comment, vote_link
)

urlpatterns = patterns('',
    url(r'^$', LinkListView.as_view(), name='home'),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}, name='login'),
    url(r'^auth/$', auth, name='auth'),
    url(r'^submit_link/$', submit_link, name='submit_link'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^register/$', register, name='register'),
    url(r'^accounts/register/$', register, name='register'),
    url(r'^r/$', subreddit_view, name='subreddits'),
    url(r'^r/(?P<sub>[\w]+)/$', subreddit_selector, name='subreddits'),
    url(r'^discuss/(?P<link>[\w-]+)/$', link_discuss, name='links'),
    url(r'^v/l/(?P<link_id>[\w-]+)/$', vote_link, name='links'),
    url(r'^v/c/(?P<comment_id>[\w-]+)/$', vote_comment, name='links'),
)

urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.threads.urls', namespace="threads")),
)

apps/threads/models.py
from django.db import models
from django.db.models import Count
from django.contrib.auth.models import User


class LinkVoteCountManager(models.Manager):
    def get_queryset(self):
        return super(LinkVoteCountManager, self).get_queryset().annotate(votes=Count('vote')).order_by('-votes')

class CommentVoteCountManager(models.Manager):
    def get_queryset(self):
        return super(CommentVoteCountManager, self).get_queryset().annotate(votes=Count('vote')).order_by('-votes')

class Subreddit(models.Model):
    title = models.TextField(max_length=30)
    slug = models.TextField(max_length=30, null=True)
    creator = models.ForeignKey(User, null=True)

class Link(models.Model):
    title = models.TextField("Headline", max_length=100)
    internal = models.TextField("Internal Link", max_length=100)
    submitter = models.ForeignKey(User)
    date_submitted = models.DateTimeField(auto_now_add=True)
    subreddit = models.ForeignKey(Subreddit, null=True, related_name="links")
    rank = models.FloatField(default=0.0) # Used for displaying links
    url = models.URLField("URL", max_length=100, blank=True)
    description = models.TextField("Description", blank=True)
    objects = LinkVoteCountManager()

    def __unicode__(self):
        return self.title


class Comment(models.Model):
    submitter = models.ForeignKey(User)
    date_submitted = models.DateTimeField(auto_now_add=True)
    rank = models.FloatField(default=0.0) # Used for displaying links
    description = models.TextField("Description", blank=True)
    link = models.ForeignKey(Link, blank=True, null=True, related_name="replies")
    comments = models.ForeignKey('self', blank=True, null=True, related_name="replies")
    objects = CommentVoteCountManager()

    def __unicode__(self):
        return self.description

class Vote(models.Model):
    voter = models.ForeignKey(User)
    link = models.ForeignKey(Link, null=True, blank=True, related_name="vote")
    comment = models.ForeignKey(Comment, null=True, blank=True, related_name="vote")

    def __unicode__(self):
        return self.voter.username

apps/threads/forms.py
from django import forms
from .models import Vote
from django.contrib.auth.models import User

class RegistrationForm(forms.ModelForm):
    '''
    Form for registering a new account.
    '''
    username = forms.CharField(widget=forms.TextInput, label="Username")
    password1 = forms.CharField(widget=forms.PasswordInput,
                                label="Password")
    password2 = forms.CharField(widget=forms.PasswordInput,
                                label="Password (again)")

    class Meta:
        model = User
        fields = ['username' , 'password1', 'password2']

    def clean(self):
        '''
        Verifies that the values entered in the password field match
        '''

        cleaned_data = super(RegistrationForm, self).clean()
        if 'password1' in cleaned_data and 'password2' in cleaned_data:
            if cleaned_data['password1'] != cleaned_data['password2']:
                raise forms.ValidationError("Passwords don't match. Please enter both fields again.")
        return cleaned_data

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

apps/threads/views.py
from django.shortcuts import render_to_response, redirect
from django.template import RequestContext
from .forms import RegistrationForm
from django.views.generic import ListView
from django.template.defaultfilters import slugify
from .models import Link, Vote, Subreddit, Comment
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.shortcuts import redirect, render
from django.shortcuts import get_object_or_404
from django.views.generic.edit import FormView
from django.http import HttpResponse


class LinkListView(ListView):
    model = Link

    def get_context_data(self, **kwargs):
        context = super(LinkListView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated():
            voted = Vote.objects.filter(voter=self.request.user)
            links_in_page = [link.id for link in context["object_list"]]
            voted = voted.filter(link_id__in=links_in_page) 
            voted = voted.values_list('link_id', flat=True)
            context["voted"] = voted
        return context

def logout_view(request):
    logout(request)
    return redirect('/')

def auth(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('/')
        else:
            return redirect('/login')
    else:
        return redirect('/login')


def subreddit_view(request):
    return render(request, 'sub_list.html', {'subreddits':Subreddit.objects.all()})

def subreddit_selector(request, sub):
    slug = slugify(sub)
    subreddit = Subreddit.objects.filter(slug=slug)
    print subreddit.count()
    if subreddit.count() > 0:
        return render(request, 'subreddit.html', {'subreddit': slug,
                                                   'links': subreddit[0].links.all()
                                                   })
    else:
        if request.method == 'POST':
            Sub = Subreddit.objects.create(title=sub, slug=slug, creator=request.user)
        return render(request, 'new_sub.html', {'subreddit': slug})

def link_discuss(request, link):
    slug = slugify(link)
    links = Link.objects.filter(internal=slug)
    comment_votes = []
    if request.user.is_authenticated == True:
        totals = Vote.objects.filter(voter=request.user)
        for item in totals:
            if item.comment != None:
               comment_votes.append(item.comment.id) 
    if request.method == 'POST':
        information =  request.POST.get('button').split()
        print information
        if information[0] == 'l':
            parent = Link.objects.get(id=information[1])
            reply = Comment.objects.create(link=parent, submitter=request.user,
             description=request.POST.get('new_comment'))
            reply.save()
        elif information[0] == 'c':
            parent = Comment.objects.get(id=information[1])
            reply = Comment.objects.create(comments=parent, submitter=request.user,
             description=request.POST.get('new_comment'))
            reply.save()
        if links.count() > 0:
            return render(request, 'link.html', {'link':links[0],
                                         'comments': links[0].replies.all(),
                                         'vote_list': comment_votes
                                         })
        else:
             return redirect('#')
    else:
        if links.count() > 0:
            return render(request, 'link.html', {'link':links[0],
                                         'comments': links[0].replies.all(),
                                         'vote_list': comment_votes
                                         })
        else:
             return redirect('/')

def submit_link(request):
    if request.method == 'POST':
        user = request.user
        title = request.POST.get('title')
        url = request.POST.get('url')

        if url[:3] != 'http':
            url = "http://" + url
        if Link.objects.filter(url=url).exists():
            return render(request, 'threads/link_list.html', {
            'object_list': Link.objects.all(),
            'repost': True,
            })    
        else: 
            description = request.POST.get('description')
            Link.objects.create(submitter=user, internal=slugify(title), title=title, url=url, description=description)
            return render(request, 'threads/link_list.html', {
                'object_list': Link.objects.all(),
                'submit': True,
                })
    else:
        return render(request, 'submit_link.html')


def register(request):
    '''
    Request View
    '''
    if request.method == 'POST':
        form = RegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = RegistrationForm()
    return render_to_response('register.html', {
        'form': form,
    }, context_instance=RequestContext(request))

def vote_comment(request, comment_id):
    if request.method == 'POST':
        print request.path
        if request.user.is_authenticated:
            comment = Comment.objects.get(id=comment_id)
            if Vote.objects.filter(comment_id=comment_id).exists():
                Vote.objects.filter(comment_id=comment_id).delete()
                return redirect(request.path)
            else:
                Vote.objects.create(voter=request.user, comment=comment)
                return redirect(request.path)
        else:
            return redirect('/login')
    else:
        return redirect('/')


def vote_link(request, link_id):
    if request.method == 'POST':
        if request.user.is_authenticated:
            link = Link.objects.get(id=link_id)
            if Vote.objects.filter(link_id=link_id).exists():
                Vote.objects.filter(link_id=link_id).delete()
                return HttpResponse('Removed')
            else:
                Vote.objects.create(voter=request.user, link=link)
                return HttpResponse('Added')
        else:
            return HttpResponse('Invalid')
        
    else:
        return redirect('/')

apps/threads/templates/base.html
<html>
<head>
  <title>Reddit Wannabe</title>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<link href='https://fonts.googleapis.com/css?family=Roboto:400,300,500' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<!-- Latest compiled and minified JavaScript -->
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <script>
  $(function() {
    $( "#accordion" ).accordion({
    	collapsible: true,
    	active: false
    });
  });
  </script>
</head>
<body>
<nav class="navbar navbar-inverse">
<div class="navbar-header">
<a href="/" class="navbar-brand">USU Reddit</a>
</div>  
  
	<div class="navbar-right">
	<ul class="nav navbar-nav">
{% if user.is_authenticated %}

	<li class="active">	
	    <a href="/logout">Logout </a>
	</li>
{% else %}
	<li class="active">	

    <a href="/login">Login</a>
	</li>
	<li class="active">	

    <a href="/register">Register</a>
	</li>

{% endif %}
	</ul>
</div>
</nav>

	
{% block content %}
{% endblock %}



</body>
<footer>


</footer>
</html>

apps/threads/templates/link.html
{% extends 'base.html' %}

{% block content %}

<div class="panel panel-default">
	<div class="panel-heading">
<h2>{{link.title}}</h2>
	</div>
	<div class="panel-body">
<p>
  {{link.description}} <br/>
</p>
	</div>
</div>
{% if user.is_authenticated%}

<div id="accordion">
	<h3> Reply </h3>
<div>
	
<p> Commenting as {{user.username}}</p>
<form action="" method="POST">
	
	<textarea name="new_comment" id="" cols="75" rows="10"></textarea>
	<hr/>
  <button value="l {{link.id}}" class="btn btn-primary btn-sm" name="button"> Submit Comment</button>
    {% csrf_token %}
</form>
</div>
</div>
{%endif%}
<ul class="list-group">
	

{% for reply in comments %}
{%with comments=reply template_name="replies.html" %}
                   {%include template_name%}
              {%endwith%}
{% endfor %}
</ul>
{% endblock %}

apps/threads/templates/login.html
{# {% extends 'auth_base.html' %} #}

{% block content %}
<div class="tb">
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}
{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'threads:auth'%}" class="fc-submit-form">
{% csrf_token %}
<table class="tb__table">
<tr class="tb__table__row">
    <td class="tb__table__row__item tb--label">{{ form.username.label_tag }}</td>
</tr>
<tr class="tb__table__row">
    <td class="tb__table__row__item">{{ form.username }}</td>
</tr>
<tr class="tb__table__row">
    <td class="tb__table__row__item tb--label">{{ form.password.label_tag }}</td>
</tr>
<tr class="tb__table__row">
    <td class="tb__table__row__item">{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" class="tb__btn"/>
<input type="hidden" name="next" value="{{ next }}" />
</form>

{# Assumes you setup the password_reset view in your URLconf #}
{# <p><a href="{% url 'reports:password_reset' %}">Lost password?</a></p> #}

</div>
{% endblock %}

apps/threads/templates/new_sub.html
{% extends 'base.html'%}
{% block content %}
<h3>It looks like that subreddit doesn't exist yet!</h3>
{% if user.is_authenticated %}
<p>
  To create this subreddit please press this button.
</p>
  <form class="" action="" method="post">
    {% csrf_token %}
      <button value="{{subreddit}}" class="btn btn-primary btn-lg disabled" name="button"> {{subreddit}}</button>
  </form>
{% else %}
<p>
  If you'd like to create it. You need to log in.
</p>
{% endif %}
{% endblock %}

apps/threads/templates/register.html
{% extends "base.html" %}
{% block title %}Register{% endblock %}
{% block content %}

  <h2>Registration</h2>

  <form action="/accounts/register/" method="post">{% csrf_token %}
    {{form.as_p}}
  <input type="submit" value="Register" />

  </form>

{% endblock %}

apps/threads/templates/replies.html
<li class="list-group-item"> 
     <span class="badge pull-left" id="votes-{{comments.id}}">{{comments.vote.all.count}}</span>
      	{% if not user.is_authenticated %}
 	<span class=badge> Log in to Vote</span>
	
 	{% elif comments.pk not in vote_list %}

 	<form action="/v/c/{{comments.id}}/" method="POST">
    		{% csrf_token %}
 	<button class="btn btn-default" id="voteButton-{{comments.id}}">Like</button>
 	</form>
    {% else %}
 	<form action="/v/c/{{comments.id}}/" method="POST">
    		{% csrf_token %}
 	<button class="btn btn-default" id="voteButton-{{comments.id}}">Unlike</button>
 	</form>
	{%endif%}
	<script>
	$('#voteButton-{{comments.id}}').click( function (){
		if( $('#voteButton-{{comments.id}}').text() == 'Like'){

		var current = parseInt($('#votes-{{comments.id}}').text());
		var newVal = current + 1;
		$('#votes-{{comments.id}}').text(newVal);
		$('#voteButton-{{comments.id}}').text('Unlike')		
		}
		else{
		var current = parseInt($('#votes-{{comments.id}}').text());
		var newVal = current - 1;
		$('#votes-{{comments.id}}').text(newVal);
		$('#voteButton-{{comments.id}}').text('Like')		
		}
		event.preventDefault();

		function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie != '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
		
		function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    	return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
		}	

		var csrftoken = getCookie('csrftoken');

		$.ajaxSetup({
    	beforeSend: function(xhr, settings) {
		        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
		            xhr.setRequestHeader("X-CSRFToken", csrftoken);
		        }
		    }
		});
		$.ajax({
			type:'POST',
			url: '/v/c/{{comments.id}}/',
			data: {
				'comment_id': {{comments.id}},
			},
			success: function(){
				console.log('Success!');
			}
		});
		return false;
	});
	</script>
		{{comments.description}} 
</li>
{% if user.is_authenticated%}
  <script>
  $(function() {
    $( "#accordion-c-{{comments.id}}" ).accordion({
    	collapsible: true,
    	active: false
    });
  });
  </script>
 <div id="accordion-c-{{comments.id}}">
 	
 <h3>Reply</h3>
 <div>
 	
<p> Commenting as {{user.username}}</p>
<form action="" method="POST">
	
	<textarea name="new_comment" id="" cols="75" rows="10"></textarea>
	<hr/>
  <button value="c {{comments.id}}" class="btn btn-primary btn-sm" name="button"> Submit Comment</button>
    {% csrf_token %}
</form>
 </div>
 </div> 
{%endif%}
	
<div class="container">
	
<ul class="list-group">
{% if comments.replies.all.exists == True  %}
{% for reply in comments.replies.all%}
{%with comments=reply template_name="replies.html" %}
                   {%include template_name%}
              {%endwith%}
{% endfor %}
{% endif %}
</ul>
</div>

apps/threads/templates/sub_list.html
 {% extends 'base.html' %}

<ul>
 {% for sub in subreddits %}
  <li> sub.title </li>
 {% endfor %}
 </ul>

apps/threads/templates/submit_link.html
{% extends 'base.html' %}

{% block content %}
{% if user.is_authenticated %}
	<div class="col-sm-10" style="padding:20px; margin-left:20%; width:60%; position:absolute;">
		<form action="" method='POST'>
			<label for="basic-url">Title</label>
			<div class="input-group">
			  <input name="title" type="text" class="form-control" id="basic-url" aria-describedby="basic-addon3">
			</div>
			<label for="basic-url">URL</label>
			<div class="input-group">
			  <input name="url" type="text" class="form-control" id="basic-url" aria-describedby="basic-addon3">
			</div>
			<label for="basic-url">Description</label>

			<textarea name="description" class="form-control"id="" cols="30" rows="10"></textarea>
			<hr/>
  			<button value="" class="btn btn-primary btn-sm pull-right" name="button"> Submit Thread</button>
    		{% csrf_token %}
			
		</form>

	</div>
{% else %}
	<div class="col-sm-10" style="padding:20px; margin-left:20%; width:60%; position:absolute;">
		<h1> You need to be <a href="/login">logged in</a> to view this page.</h1>
	</div>


{% endif %}
{% endblock %}

apps/threads/templates/subreddit.html
{% extends 'base.html' %}

{% block content %}

<h3>{{subreddit.title}}</h3>
{% for link in links%}
<li> link.title </li>
{% endfor %}
{% endblock %}